version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: callcenter_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=cAgckF9S6aTF8rRWXY8j
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    command: |
      bash -c "
      if [ ! -d /usr/share/elasticsearch/plugins/analysis-ik ]; then
        echo 'Installing IK analyzer...'
        bin/elasticsearch-plugin install -b https://get.infini.cloud/elasticsearch/analysis-ik/8.13.0
      fi
      exec /usr/local/bin/docker-entrypoint.sh eswrapper
      "

volumes:
  es_data:
