listening-port=3478
tls-listening-port=5349
realm=callcenter.local
server-name=callcenter-turn
user=callcenter:Trustfar2026!
external-ip=101.251.208.178/172.31.0.22
fingerprint
lt-cred-mech
log-file=/var/log/turnserver.log
no-cli
